[supabase]
url = "https://fuwesmrejgwepfrwqxeb.supabase.co/rest/v1/"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1d2VzbXJlamd3ZXBmcndxeGViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY5Mjc1OTUsImV4cCI6MjEwMjUwMzU5NX0.54yvlyDhJtlG64DgQHO5hQkh9uzzIEiqH4hlHN8XsWo"
